version: '3.3'
services:

  # Database Service (Mysql)
  mysql:
    image: mysql:5.6
    container_name: myWorkr
    ports:
      - "3307:3307"
    restart: always
    environment:
      MYSQL_DATABASE: workrdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - workr-mysql:/var/lib/mysql

  java:
    depends_on:
      - mysql
    ports:
      - "80:8080"
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/lib/mysql
    links:
      - mysql
volumes:
  workr-mysql: